### ISSUE TITLE
Captain Sander's Treasure Map Bugged Droprate

### ISSUE THREAD

**Issue by hoggswow** [TheBarrens/mangos-classic#57]
What happens currently: The drop rate is either extremely low or doesn't drop at all.

What should happen: 100% Drop rate for the quest starter from all westfall murlocs.

How to reproduce: Go to westfall, kill any murloc along the coastline and the quest starter will not drop.

[Evidence of Droprate](http://db.vanillagaming.org/?item=1357)
[GIF Evidence](https://gyazo.com/078d4ac3926d49a3708cc9799db4f46f)

**Comment by Tixlenra** [comment]
Leaving report for Fuzedknight as he has dealt with all quest item droprates in the game from a verified source.

**Comment by Fuzedknight** [comment]
100% drop rate is a private server bug. Using private server databases to find drop rates is usually a bad idea. The only reason it seems to be correct universally as no other server has ever addressed the buggy drop rates. It's not supposed to have that high of a rate, on top of the evidence piled above I'd also like to present a pre WoWhead's databases opinion on the matter.

https://web.archive.org/web/20050216190011/http://wow.allakhazam.com:80/db/item.html?witem=1357

This is dated 2005 and claims the drop rate is close to 0.70%, however even these old databases aren't 100% accurate. Due to the fact that people killing the Murlocs who have done the quest are also considered in the database so it's more of a guess with a general area. The current database drop rate is 1.77% but I can adjust it by a few 0.%s if it feels too low.
